[[permission]]
identifier = "allow-app-commands"
description = "Allows invoking custom application commands on remote origins"

[permission.commands]
allow = [
  "get_app_config",
  "update_app_config",
  "auto_connect",
  "save_file_to_disk",
  "check_for_updates_api",
  "start_update",
  "open_url",
  "get_version"
]
